### ISSUE TITLE
Fun Idea: format output of mcd as input to libRadtran

### ISSUE THREAD

**Issue by aaronreichmenberliner** [aymeric-spiga/mcd-python#37]
I want to calculate the spectral flux at any time/location on Mars. The output of mcd should be sufficient to define an input `.INP` file for [libRadtran](http://www.libradtran.org/doku.php?id=start).

**Comment by aymeric-spiga** [comment]
Some fluxes are available in the Mars Climate Database https://github.com/aymeric-spiga/mcd-python/blob/416c472b35cdbc9fd82fe8324acdae123c028f14/mcd.py#L190 that are computed by the radiative transfer of the Global Climate Model, from which the MCD is derived.

Or do you have a specific need?

**Comment by aaronreichmenberliner** [comment]
Yes I saw that! Super awesome. But I need the spectral irradiance from ~200-2000 nm for my calculations.

**Comment by aymeric-spiga** [comment]
Yes this will not be in the MCD. Our GCM uses outputs from line-by-line modeling to define absorption in "channels" so that the radiative transfer in the GCM does not take forever. In that case, it would make sense thus to take the atmospheric state from the MCD and input this in libRadtran. This is a use that some MCD users are doing e.g. when using the MCD in retrievals, trying to fit a synthetic spectra to e.g. spectra measured by orbiting spacecraft

**Comment by aymeric-spiga** [comment]
I will close this issue, but if you happen to write a small script to format `.INP` files for `libRadtran`, you are welcome to submit a pull request so that I'll include this in the Python part. Thanks!
